
// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  REST_API_URL: 'http://localhost:8080',
  CLIENT_ID: 'eara',
  CLIENT_SECRET: 'eara'
};
